### ISSUE TITLE
Digital Framework update

### ISSUE THREAD

**Issue by Dianadec** [bcgov/digital.gov.bc.ca#129]
Given delays in publishing updates about the digital framework, this Epic was rescoped to accomplish research and design work that can be implemented in a future release.

# Acceptance Criteria (TBC)
- The Framework page displays the commitments and the status of each
- The user can explore the details of each priority action/commitment

**Comment by mark-a-wilson** [comment]
@nmathava , @HeatherRemacle - May I suggest that we close this Epic and override it with #341? 

Lots of good stuff in here, it's just geared towards a different user. It seems to me that with #341 and epics like it, we're turning our focus to be enabling content owners to publish _their own content_ that meets _their users' needs_, rather than to also take responsibility for how all of the content meets/doesn't meet users needs.

**Comment by HeatherRemacle** [comment]
@mark-a-wilson These are two different, and relevant, user stories. I'd like to keep both. For this one, the associated tickets are mostly about the design of the page, and the structuring of the site to enable appropriate navigation to related elements of the Framework.

Testing this ticket would include asking non-OCIO folks if the content/design helps them understand the framework (front stage)

Testing ticket #341 would be focused on Kim's experience applying those insights and adding/updating content (back stage).

Does that jive with your thinking?

**Comment by mark-a-wilson** [comment]
Yep, that makes sense. I was just attempting to "offload" the responsibility for testing the efficacy of the content to the content owners/authors. 😇

**Comment by mark-a-wilson** [comment]
We have created designs and a clickable mockup in Figma (see #288) based on all of the content that has been provided to date. Will add new tasks to the Backlog related to this epic as they become necessary.
