### ISSUE TITLE
Fix card grid

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#362]
Whatever container or grid in which groups of cards are contained seems to be to narrow at certain breakpoints. This causes:
- [ ] Two columns to be squished into too narrow of a container:

![card-grid-too-narrow-1](https://user-images.githubusercontent.com/16946297/96905238-0f7fc080-144d-11eb-9232-07f2a545365d.png)

- [ ] One column to have too much margin on each side:
 
![card-grid-too-narrow-2](https://user-images.githubusercontent.com/16946297/96905509-638aa500-144d-11eb-805c-61b14e08eaf0.png)

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist: 

It appears that in most places we are using a 12-column grid imported from [react-flexbox-grid](https://roylee0704.github.io/react-flexbox-grid/). I'm wondering, because we are using Ant Design components (e.g. cards) elsewhere, should we refactor the 12-column stuff to Ant Design's [24-column grid](https://ant.design/components/grid/), so that we can more easily use more of Ant Design's boilerplate components?

**Comment by mark-a-wilson** [comment]
Pushed a branch, [issue-362](https://github.com/bcgov/digital.gov.bc.ca/tree/issue-362). Jon is going to talk me through some suggestions at 2:00.

**Comment by mark-a-wilson** [comment]
Had good critique/tutorial from Jon. Will define this issue a bit better, then re-start a fresh branch and start submitting small PRs.

**Comment by mark-a-wilson** [comment]
Can't get develop to compile locally -- reaching out to Jon and Parul on Teams....

![image.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/62015068-77a3-4e4c-a4b8-97a3126b2d78)

**Comment by mark-a-wilson** [comment]
These issues were identified on the Home page. They seem to have been inadvertently fixed now as I look at a deployment of prod: https://digital-gov-frontend-prod-xdwiwd-prod.pathfinder.gov.bc.ca. Closing
