### ISSUE TITLE
Implement new banner on select pages, style fixes 

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#379]
This is blocked by the creation of the new banner #378
AC: Implement new page banner on the following pages:
Home Page
Digital Framework
Digital Principles
Products & Services
Resources

Clean up of styling on these pages is occurring at the same time

**Comment by singhinderdeep** [comment]
Home Page
Digital Framework
Digital Principles
Products & Services 
Resources
Community
Case studies

**Comment by thegentlemanphysicist** [comment]
- ~Home Page~ merged in
- ~Digital Framework~ pr up
- Digital Principles
- Products & Services
- Resources

**Comment by thegentlemanphysicist** [comment]
https://digital-gov-frontend-pr-401-xdwiwd-dev.pathfinder.gov.bc.ca/

**Comment by HeatherRemacle** [comment]
Thanks for your work on this. I'd like to tighten up the spacing for all the pages except the home page. There is a bunch of space around the breadcrumbs, and it's not consistent when I arrive on a page - sometimes all I see is the heading and other times I can see the content below as well. I like the feel of the home page - where the heading does not take that much space.

Thoughts @singhinderdeep ?

![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/a2974bf6-0446-4a2f-80c4-b6b73c7b082e)

**Comment by singhinderdeep** [comment]
Wow :O that definitely is too much space 

Suggestion : Me and @mark-a-wilson discussed this earlier and thought we might not really need the breadcrumbs, since pretty much all of our content is just one level away from home. So, we might be better off taking the breadcrumbs away and probably can have the Digital Framework, Digital Principles, Community and Case Studies in navbar itself. We also got this feedback in our user research that people were expecting the first two cards (Digital Framework and Digital Principles) in the navbar when we have the third and fourth card (Resources and Products & Services).

Does that sound good?

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - Inder, Jon and I discussed this morning and: 

1. Spacing of the breadcrumb will get reduced and its position aligned in #359 that Jon is currently working on
2. The breadcrumb does seem silly on Level 1 pages (e.g. Resources, Products & Services); however, it is still useful on Level 2 and beyond pages (e.g. Digital Principles). I will create a ticket in the backlog to look at defining whether a page contains the breadcrumb or not (we may already have this ability because Home doesn't display it). 
3. We agreed it makes sense to add some more links to the main navigation (e.g. Case Studies, Digital Framework, in addition to Marketplace) I will simply add these to the scope of #390.
4. We agreed it makes sense to remove 'Home' from the navigation bar -- it's redundant when 'Home' always appears in the breadcrumb, and in addition, we'll be making the header logo/title clickable to go back to the homepage (see #412)
