### ISSUE TITLE
Common Components implementation planning

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#396]
We need to explore the options for publishing common components content, based on the user research/design completed by the CoCo team.

Executive engagement/ direction required regarding resourcing.

Consider the least of amount of work we can do to meet user needs (MVP)

# Acceptance Criteria

- [ ] Clarify the function of DevHub that might support publishing CoCos (identify value/opportunity)
- [ ] Clarify the function of Digital.gov.bc.ca that might support publishing CoCos
- [ ] Clarify the best option for publishing, and determine the amount of work to publish in the short and long term (resourcing plan)

# Definition of Done
- [ ] Decision note/ 1-2 pager with options

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - does this capture what you need out of this task?

### User Story

As the **product owner** of digital.gov.bc.ca, I would like a presentation that lays out different options, and recommendations, for how a **catalogue of common components** could be **_published and maintained_** and the different decisions that need to be made, so that I can: 

- more realistically anticipate how much impact undertaking the implementation and maintenance of a catalogue will have on my team's capacity and, in that light, weigh it against other initiatives I might want my team to undertake 
- communicate to my executive sponsors and stakeholders what resources I will need if I am being asked to publish and sustain a catalogue
- make a decision on whether and how I will direct my team to implement a common components catalogue

### Acceptance Criteria

A presentation deck or document is delivered to Heather that provides (1) a discussion of options and (2) a recommendation regarding each of the following questions:

#### Initial design & build

1. **Where** online should the common components catalogue reside? Does it belong on DevHub/Components, and if so, what content is necessary on digital.gov.bc.ca to point to it there?
2. Who will decide on the scope of design (or design enhancements) that need to be implemented? (Who will be the product owner of the catalogue?)
3. Which staff and/or contractors will do the design and development work to implement the catalogue? 

#### Governance

1. Who will decide which common components should be published (i.e. endorsed, recommended)?
2. Who will be responsible for providing/writing the necessary information about a common component and keeping that information up-to-date?
3. How will the information about each common component be initially published (i.e. hard-coded? MarkDown -> DevHub? CMS?)
4. How will new components and their information be added to the catalogue and edits to existing components be made?
5. Will ongoing work be done to: research how the catalogue meets user needs and to design and implement improvements to the catalogue? Who will be responsible for this?

**Comment by mark-a-wilson** [comment]
Hi @HeatherRemacle, 

[Here is a link](https://teams.microsoft.com/l/file/B767F919-14B6-4B10-98A5-34D4426EC73C?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F00109-digital.gov.bc.ca%2FShared%20Documents%2Fdigital.gov.bc.ca%2FCommon-components-concept%2FCommon%20Components%20Implementation%20Planning.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F00109-digital.gov.bc.ca&serviceName=teams&threadId=19:f78c23767e214080840d1b7e37bd91d7@thread.tacv2&groupId=f56865b7-57f7-419c-903d-0611fc8b3b54) to the doc I was working on. I don't believe we need to follow through with this because as a result of our Nov 2 we seemed to agree on a clear goal and plan which is reflected in #345.
