### ISSUE TITLE
Strapi content resets to being hidden from public when PRs are redeployed

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#627]
@thegentlemanphysicist — Here's my understanding of what's happening. Please go ahead and edit this description of the bug. 

#### Problem
With PR #625, it seems that every time new changes are pushed to the PR (triggering a redeployment, I think?), new Strapi content related to that PR gets reset to being hidden from the public by default. 

e.g. The Communities content was visible on the deployment, but after redeployment, the content is now hidden:

![content.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/7069730a-8eba-49af-80e2-de25aa661e6d)

#### Desired outcome
We can redeploy PRs without resetting Strapi content settings

**Comment by thegentlemanphysicist** [comment]
@mark-a-wilson The cause of this bug is that there are two versions of strapi pointing at the same instance of the mongo database.  These two versions of strapi have different content type models.  Whichever version of strapi was most recently deployed overwrites the previous deployments, causing the fields to be hidden on the previous deployment.
Proposed Solutions:
- Only ever have a single PR up in dev 
- Only have a single instance of strapi that all dev frontends point at 
- Have an instance of mongo deployed for each instance of strapi in dev so that we can have multiple prs up at once

Either way this is a systems design decision that will need to be discussed as a team.
