### ISSUE TITLE
Migrate data from Test to Dev

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#635]

**Comment by nmathava** [comment]
As per steps to resolving issues with multiple instances of Strapi. We are exploring the feasibility of migrating test database to dev namespace. 

### Acceptance:

Parul to look into options.

**Comment by thegentlemanphysicist** [comment]
@parulmishra I had a couple of questions about this process:

- Is there a script that can be run to do this or is it a very involved process?
- Is it possible to leave the users (usernames, login credentials, permissions) out of the migration?  Or will the dev credentials get overwritten by the test credentials?  They are generated by strapi and stored in the database.

I did notice that the images don't migrate over, though that's not a huge surprise since they are are stored in a separate PVC. Not a huge issue, but something that might be worth investigating down the road.

**Comment by parulmishra** [comment]
@thegentlemanphysicist 
1) There is no script to do the migration from test to dev. As it was a one time task for the purpose of testing strapi's capability. Hence it was done manually.
2) Whatever is stored in the mongo database in test environment will move to mongo database in dev environment. Strapi usage of Mongo is a blackbox to me. Do we have a whitelisted set of tables collections that needs to be migrated? Or a blacklisted set of collections that don't need to be migrated?
3) As you said the images are in a separate PVC, hence moving images is out of the scope of this ticket. This is specifically for moving data from mongo database in test environment to mongo database in dev environment. We can create another ticket to move images.

**Comment by thegentlemanphysicist** [comment]
The one part I think is worth looking into in future work is white/blacklisting the user tables, but the actual table names for those isn't something I currently know.
