### ISSUE TITLE
Integrate past classes into Learning page

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#810]
#### Description of Task 
When looking at the BCDevExchange Learning page we realized the system is not displaying past classes.  Ari mentioned that it would be nice to have these displayed so that site users know that we have them.  This is outside the current design scope for the learning page ticket however it may be a useful feature to develop in the future.

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)
- [ ] Speak to Ari and update wireframes

**Comment by thegentlemanphysicist** [comment]
pending Ari's return from vacation.

**Comment by singhinderdeep** [comment]
As discussed in the standup, acceptance criteria needs to change for this and should be updated with the requirements that Ari has for the Learninig page, which are mentioned below

- To have one instance of each course offering that we have instead of just showing the upcoming courses
- To allow users to express their interest for a particular course to better know which course is in demand and Ari could plan accordingly.

Need to create more tickets, especially for Jon to look into the technical feasibility of it.
