### ISSUE TITLE
Change the unique id to headings

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#829]
#### Description of Task 

- Change the unique id under **Why should I use this?** and **Who else is using this?** sections to headings

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- The alphanumeric unique ids are changed to the Headings text.

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist -- for **Who Is Using This**, could it be made so that the **Ministry** selected is displayed on the accordion header instead of "Create an entry"? 

![Screen Shot 2021-08-30 at 9.20.24 AM.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/ff82dc1a-7191-4198-b05b-be3a04833f47)

**Comment by thegentlemanphysicist** [comment]
@mark-a-wilson  Nope, that doesn't work
