### ISSUE TITLE
[DESIGN] Home Page

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#92]
# Acceptance Criteria
-  Complete the design with images
- Apply design system elements
- Mobile and web views work
- Accessibility

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - Moving this Issue on behalf of @singhinderdeep who did the work. You can view the  design wireframes [here on the Prototype board](https://miro.com/app/board/o9J_kslEIZ4=/?moveToWidget=3074457348200785828&cot=13).  We are making the wireframes in a Figma file (have just invited you to that in case you want to see it there too) so that @ryleyw can grab the design specs (sizing, spacing, etc.) as he builds the pages. We are aligning to specs defined in the Design System; and when we want to make something that's not defined in the Design System, we will attempt to make it a component and offer it back to the Design System for consideration.

**Comment by Dianadec** [comment]
I've labelled this as Sprint 2 to be included in that milestone for tracking purposes.

**Comment by mark-a-wilson** [comment]
Appears we have duplication between this and #60

**Comment by HeatherRemacle** [comment]
@singhinderdeep  I have reviewed the designs and left some comments in Figma. Acceptance criteria includes these pages including images. Are those elsewhere? What did Ryley code into the pages that are supposed to be working?
